### ISSUE TITLE
What is in the "/data00/user1/data/corenlp/"

### ISSUE THREAD

**Issue by haha-lisa** [JosephPai/Art-Description#1]
![微信图片_20211026135314](https://user-images.githubusercontent.com/65552265/138816935-6117497d-1d4e-455f-b20b-1e8eab59571d.png)
Thank you for your creative work! But could you please tell me that what is in the "/data00/user1/data/corenlp/"?

**Comment by JosephPai** [comment]
Please refer to [python-stanford-corenlp](https://github.com/stanfordnlp/python-stanford-corenlp)
